<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>io.debezium.examples.otel</groupId>
	<artifactId>otel-e2e</artifactId>
	<version>0.0.1</version>
	<packaging>pom</packaging>
	<name>OTEL E2E Root Module</name>
	<modules>
		<module>service-one</module>
		<module>service-two</module>
	</modules>
</project>
