receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otel-collector:4317"
      http:
        endpoint: "otel-collector:4318"
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  debug:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]
