spring.application.name=service-two

#Kafka configurations
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=DebeziumEventGroup
spring.kafka.listener.missing-topics-fatal=false

# Enable debug logging
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.security.oauth2=DEBUG
#logging.level.org.springframework.boot=debug
